name: statistics
description: Statistics package for easy and efficient data manipulation with built-in Bayesian Network (Bayes Net), many mathematical functions and tools.
version: 1.0.17
homepage: https://github.com/gmpassos/statistics

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ^0.17.0
  collection: ^1.15.0
  data_serializer: ^1.0.7

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.9
  dependency_validator: ^3.1.0
  coverage: ^1.0.3

#dependency_overrides:
#  data_serializer:
#    path: ../data_serializer

