name: statistics
description: Statistics package for easy and efficient data manipulation with many built-in mathematical functions and tools.
version: 1.0.14
homepage: https://github.com/gmpassos/statistics

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ^0.17.0
  collection: ^1.15.0
  data_serializer: ^1.0.3

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.9
  dependency_validator: ^3.1.0
  coverage: ^1.0.3
