name: statistics
description: Statistics package for easy and efficient data manipulation with built-in Bayesian Network (Bayes Net), many mathematical functions and tools.
version: 1.0.22
homepage: https://github.com/gmpassos/statistics

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  intl: ^0.17.0
  collection: ^1.16.0
  data_serializer: ^1.0.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
  dependency_validator: ^3.2.2
  coverage: ^1.2.0

#dependency_overrides:
#  data_serializer:
#    path: ../data_serializer

